[build]
  publish = "./"
  command = ""

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[headers]]
  for = "/*"
  [headers.values]
  Content-Security-Policy = """
    default-src 'self';
    style-src 'self' https://fonts.googleapis.com;
    font-src https://fonts.gstatic.com;
    script-src 'self';
    object-src 'none';
    base-uri 'none';
    form-action 'none';
  """
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "DENY"
  Referrer-Policy = "strict-origin-when-cross-origin"
  X-XSS-Protection = "1; mode=block"

